"INPUT_MODE": "full_state"
"ENV_NAME": "MPE_simple_spread_v3"
"ENV_KWARGS": {}

# Match the official IPPO-RNN optimization regime.
"LR": 5e-4
"NUM_ENVS": 16
"NUM_STEPS": 128
"FC_DIM_SIZE": 128
"FF_LATENT_DIM": 128
"TOTAL_TIMESTEPS": 1e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.3
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.5
"ANNEAL_LR": True
"SEED": 30

# WandB
"ENTITY": "yachen-tian-rwth-aachen-university"
"PROJECT": "jaxmarl-mpe"
"WANDB_MODE": "online"
